style='<meta charset="UTF-8"><meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>QQ Group Photo downloader</title><style type="text/css">body{margin:0;padding:0;font-family:"Microsoft yahei","微软雅黑","Tahoma","Verdana","Arial","sans-serif";font-size:100%;line-height:1.5;color:#222;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;display:block;background-color:#eee;}div#gallery img{padding:10px 10px 20px 10px;background-color:white;margin:10px;width:200px;float:left;}div#gallery img:hover{-moz-transform:scale(1.5);-webkit-transform:scale(1.5);-o-transform:scale(1.5);-ms-transform:scale(1.5);transform:scale(1.5);box-shadow:1px 1px 10px black;}div#controlbar{position:fixed;top:0px;left:0px;display:block;width:200px;height:100%;background-color:#2C3E50;}div#controlbar button{width:140px;height:140px;padding:5px;margin:5px 10%;color:white;border:none;cursor:pointer;font-size:3em;border-radius:20000px;-webkit-border-radius:20000px;-moz-border-radius:20000px;-o-border-radius:20000px;-ms-border-radius:20000px;}button#size200{background-color:#E74C3C;}button#size400{background-color:#2ECC71;}button#size800{background-color:#F1C40F;}#size200:hover{background-color:rgb(255,145,134);}#size400:hover{background-color:rgb(107,238,163);}#size800:hover{background-color:rgb(252,227,127);}div#controlbar p#info{display:block;padding:5px 10px;background-color:rgba(128,187,241,0.43);color:white;}div#gallery{margin-left:222px;}</style>';
script = '<script type="text/javascript">window.onload=function(){var aa=document.createElement("a");if(aa.hasOwnProperty("download")==false){if(confirm("Your Broswer does not support the download HTML5 attribute,please download the latest Google Chrome Broswer!")==true){window.open("https://www.google.com/intl/zh-CN/chrome/browser/?hl=zh-CN")}}};function downloader(size){if(size==undefined){size=800};var linkphotos=document.getElementsByTagName("a"),linkphotos_size=linkphotos.length;for(var i=0;i<linkphotos_size;++i){linkphotos[i].href=linkphotos[i].href.slice(0,linkphotos[i].href.length-3)+size;linkphotos[i].click()}};</script>';
album = document.querySelectorAll("img.js-group-photo");
album_size = album.length;
html = "data:text/html," + style + '<a href="https://github.com/qibinlou/QQ-Group-Photo-Downloader"><img style="position: fixed; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a><div id="controlbar">	<p id="info">There are '+ album_size +' photos in total with width = 200,400,800. Please choose the right size to download!</p>	<button id="size200" onclick="downloader(200);" title="download photos with width = 200">200</button>	<button id="size400" onclick="downloader(400);" title="download photos with width = 400">400</button>	<button id="size800" onclick="downloader(800);" title="download photos with width = 800">800</button></div><div id="gallery">';

for(var i = 0; i < album_size; ++i)
{
	html += "<a href='"+ (album[i].src.slice(0,album[i].src.length-3) + 800) +"' download='"+ album[i].alt +"'><img src='"+ album[i].src +"'></a>";
}
html += "</div>" + script;
window.open (html);